[package]
name = "day17_trick_shot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_bench"
harness = false